/**
 * Static anti-criteria over the tree (ISC-139, ISC-165, ISC-199).
 *
 * WHY THESE ARE TESTS AND NOT A CHECKLIST. An `Anti:` criterion asserts an
 * ABSENCE, and an absence is the one claim a passing test suite cannot make on
 * its own — every one of these is satisfied today by a codebase that simply
 * has not done the forbidden thing yet. What earns the criterion is a probe
 * that would NOTICE if it started, so each guard below is mutation-verified:
 * a deliberately planted violation makes it fail. A guard nobody has seen fail
 * is indistinguishable from a guard that cannot fail.
 *
 * ISC-137 and ISC-138 have the same shape and live in
 * `test/unit/rpc-client.test.ts` under "static anti-criteria over src/",
 * because they are specifically about the RPC line splitter. They are not
 * duplicated here.
 */

import { describe, expect, test } from "bun:test";
import { join } from "node:path";

import { stripComments } from "../support/source-structure.ts";

const ROOT = new URL("../../", import.meta.url).pathname;

async function filesUnder(pattern: string): Promise<string[]> {
  const glob = new Bun.Glob(pattern);
  const out: string[] = [];
  for await (const f of glob.scan({ cwd: ROOT })) out.push(f);
  return out.sort();
}

const read = (rel: string): Promise<string> => Bun.file(join(ROOT, rel)).text();

// ---------------------------------------------------------------------------
// ISC-139 — no generated commit, branch, or PR body carries AI attribution
// ---------------------------------------------------------------------------

describe("no generated git artifact carries AI attribution (ISC-139)", () => {
  /**
   * The attribution vocabulary — PHRASING, not vocabulary items.
   *
   * A first draft of this guard banned the bare tokens `claude`, `anthropic`
   * and `copilot` anywhere under `src/`, and it went red immediately on six
   * legitimate sites: `CLAUDE.md` is a FILENAME this tool has to know about,
   * because `src/security/repo-hazards.ts` scans repository instruction files
   * and `src/run/worktree.ts` reasons about a clone that carries one. Banning
   * the name of an agent that pifleet exists to drive would be a guard that
   * fires on the subject matter rather than on the defect.
   *
   * So the patterns below match ATTRIBUTION CONSTRUCTIONS — a trailer, a
   * "generated by" credit, an "AI-assisted" label — which have no legitimate
   * use in this source tree, rather than tokens which plainly do.
   */
  const ATTRIBUTION = [
    /Co-?Authored-?By/i,
    /generated\s+(?:with|by)\s+[^\n]{0,40}?(?:claude|copilot|cursor|codex|chatgpt|gpt-)/i,
    /(?:AI|LLM)-(?:generated|assisted|authored|written)/i,
    /written\s+by\s+(?:an?\s+)?(?:AI|LLM)/i,
  ];

  test("no source file under src/ contains an attribution construction", async () => {
    for (const rel of await filesUnder("src/**/*.ts")) {
      const text = await read(rel);
      for (const re of ATTRIBUTION) {
        expect(re.test(text), `${rel} contains an AI-attribution construction (${re})`).toBe(
          false,
        );
      }
    }
  });

  /**
   * The one git artifact this tool actually generates, pinned by behaviour.
   *
   * `workerBranch` is the whole surface: pifleet writes branch names and
   * nothing else (see the capability pin below). Its output is three inputs
   * joined by slashes, and this asserts exactly that — so a later edit that
   * appends a suffix, a tag, or a credit to the branch name fails here rather
   * than being caught by a reader of `git branch` output months later.
   */
  test("a generated branch name is its three inputs and nothing else", async () => {
    const { workerBranch } = await import("../../src/run/paths.ts");
    expect(workerBranch("fleet", "2026-07-27T00-00-00Z-aaaa", "sre-1")).toBe(
      "fleet/2026-07-27T00-00-00Z-aaaa/sre-1",
    );
    // No component is decorated, and none is dropped.
    expect(workerBranch("p", "r", "w")).toBe("p/r/w");
  });

  /**
   * THE CAPABILITY PIN, and the more useful half of this criterion.
   *
   * Two thirds of what ISC-139 names cannot be violated by this tool as it
   * stands: pifleet creates BRANCHES and WORKTREES, but it never commits and
   * never opens a pull request. Measured by enumerating the git subcommands
   * that appear as argv literals under `src/`: add, branch, checkout, config,
   * diff, log, rev-parse, status, symbolic-ref, worktree — no `commit`, no
   * `push`, no `gh`.
   *
   * That makes "no generated COMMIT or PR BODY carries attribution" VACUOUSLY
   * true, and a criterion that is vacuously true is exactly the kind that
   * rots: someone adds `git commit` for a good reason, the vacuous clause
   * silently becomes a live one, and nothing notices. So the guard does not
   * assert the absence of attribution in commit messages — there are none. It
   * asserts the absence of the CAPABILITY, and fails loudly the day that
   * changes, with a message saying what the new author has to add.
   */
  test("pifleet still generates no commits and no pull requests", async () => {
    const FORBIDDEN = [
      { verb: "commit", re: /["'`]commit["'`]/ },
      { verb: "push", re: /["'`]push["'`]/ },
      { verb: "gh", re: /["'`]gh["'`]/ },
    ];
    /**
     * Comments are stripped before the match, and the reason is a measured
     * false positive rather than a tidy-up.
     *
     * `src/harvest/outbox.ts` acquired the docstring "Every exit that is not
     * the final `push` closes the descriptor first" — prose about
     * `Array.prototype.push`, in backticks because that is how one spells a
     * method name in a comment. The pin read it as an argv literal and failed
     * the build. The criterion is about a git subcommand appearing as an ARGV
     * LITERAL; a method name in a docstring is not one, and forcing prose to
     * avoid ordinary English to appease a regex makes the code worse and the
     * guard less trusted.
     *
     * Stripped CONSERVATIVELY, so the tightening cannot hide a real call:
     * block comments, and whole-line `//` comments only. A TRAILING comment is
     * deliberately left in the scanned text — `spawn(["git", "push"]) // ok`
     * still fails, which is the direction to err in.
     */
    const stripComments = (src: string): string =>
      src
        .replace(/\/\*[\s\S]*?\*\//g, " ")
        .replace(/^[ \t]*\/\/.*$/gm, " ");
    for (const rel of await filesUnder("src/**/*.ts")) {
      const text = stripComments(await read(rel));
      for (const { verb, re } of FORBIDDEN) {
        expect(
          re.test(text),
          `${rel} appears to invoke git/gh "${verb}". ISC-139's commit and ` +
            `pull-request clauses were vacuous because this tool generated ` +
            `neither. If that is changing, extend the attribution guard above ` +
            `to cover the generated message body, then update this pin.`,
        ).toBe(false);
      }
    }
  });
});

// ---------------------------------------------------------------------------
// ISC-165 — a `:ro` refusal must be a refusal, not an absence
// ---------------------------------------------------------------------------

/**
 * Split a test file into per-test bodies. Crude on purpose: an exact parse
 * would need the TypeScript AST, and the property being checked is a
 * co-occurrence within one test, which chunking on the test boundary captures.
 * Over-chunking would only ever make the guard STRICTER (a read assertion in a
 * neighbouring test would not be credited), never more permissive.
 */
function testBodies(text: string): string[] {
  return text.split(/\n\s*(?:it|test)\s*\(/);
}

describe("a :ro refusal test proves the mount was readable first (ISC-165)", () => {
  /** A write was rejected: the command came back nonzero. */
  const REFUSAL = /\.code\s*\)\s*\.not\.toBe\(\s*0\s*\)|\.code\s*\)\s*\.toBe\(\s*[1-9]/;
  /** Something was actually read back out of the mount. */
  const READ = /\.stdout\s*\)\s*\.toContain\(|readFile\(/;

  test("every :ro write-refusal test also asserts a successful read", async () => {
    const files = [...(await filesUnder("test/**/*.test.ts"))];
    let checked = 0;
    for (const rel of files) {
      const text = await read(rel);
      if (!text.includes(":ro")) continue;
      for (const body of testBodies(text)) {
        if (!body.includes(":ro")) continue;
        if (!REFUSAL.test(body)) continue; // not a refusal test; nothing to prove
        checked += 1;
        const name = body.slice(0, body.indexOf("\n")).trim();
        expect(
          READ.test(body),
          `${rel}: a :ro refusal test asserts a write was rejected but never ` +
            `reads from the mount, so it passes identically against a mount ` +
            `that is simply ABSENT (an empty mount refuses writes too). ` +
            `Read a host-written file first. Test: ${name}`,
        ).toBe(true);
      }
    }
    // If this reaches zero the guard has stopped guarding anything — the
    // refusal tests were renamed or deleted and nobody noticed.
    expect(checked, "no :ro refusal test was found to check").toBeGreaterThan(0);
  });
});

// ---------------------------------------------------------------------------
// ISC-199 — no assertion encodes a platform-specific POSIX spelling
// ---------------------------------------------------------------------------

describe("no assertion encodes a platform-specific POSIX spelling (ISC-199)", () => {
  /**
   * `ps` is the standing example and the one the criterion names: a detached
   * process prints `??` for its tty on macOS and `?` on Linux, and `ps -o
   * sess=` prints 0 for everything on macOS while Linux reports a real session
   * id. An assertion that pins either spelling is green on the machine it was
   * written on and red on the other, which is the same "suite you learn to
   * discount" failure ISC-266 is about, arrived at through portability.
   *
   * Spawning `ps` is fine and several tests legitimately do. Comparing its
   * output against a hardcoded platform spelling is what this bans.
   */
  const PLATFORM_SPELLINGS = [
    { what: "a literal ?? tty spelling", re: /toBe\(\s*["'`]\?\??["'`]\s*\)|toContain\(\s*["'`]\?\?["'`]\s*\)/ },
    { what: "an exact ps session-id value", re: /sess=[^"'`\n]*["'`]\s*\)\s*\.toBe\(/ },
  ];

  test("no test asserts a hardcoded ps output spelling", async () => {
    for (const rel of await filesUnder("test/**/*.test.ts")) {
      const text = await read(rel);
      for (const { what, re } of PLATFORM_SPELLINGS) {
        expect(re.test(text), `${rel} asserts ${what}; it will differ across platforms`).toBe(
          false,
        );
      }
    }
  });
});

// ---------------------------------------------------------------------------
// ISC-140 — the headless acceptance suite costs nothing and dials nothing
// ---------------------------------------------------------------------------

describe("no headless acceptance test needs provider spend or a cloud endpoint (ISC-140)", () => {
  /**
   * `test/e2e/` IS the headless acceptance suite — `lifecycle.test.ts` opens by
   * naming its own contract, "no Docker, no network, no GUI (ISC-19,
   * ISC-128)". ISC-21 already holds the network half of that. This is the
   * money half, and the two fail differently: a test that needs egress fails
   * closed on an air-gapped runner and everybody finds out, while a test that
   * needs provider spend PASSES and quietly bills someone. That asymmetry is
   * why it earns its own probe rather than riding on ISC-21's.
   *
   * Measured at the time of writing: the only environment variables the suite
   * touches are `PIFLEET_RUNS_DIR` and `PIFLEET_PI_*`, and it contains no URL
   * at all.
   */
  const SPEND = [
    { what: "a provider API key", re: /\b[A-Z][A-Z0-9_]*(?:API_KEY|SECRET|TOKEN)\b/ },
    { what: "an http(s) endpoint", re: /https?:\/\// },
  ];
  /** Localhost is not a cloud endpoint and not spend; a fixture may name it. */
  const LOCAL = /^https?:\/\/(?:127\.0\.0\.1|localhost|\[::1\])/;

  test("the e2e suite names no provider credential and no remote endpoint", async () => {
    const files = await filesUnder("test/e2e/**/*.test.ts");
    expect(files.length, "no e2e files found; the guard is pointing at nothing").toBeGreaterThan(
      0,
    );
    for (const rel of files) {
      const text = await read(rel);
      for (const { what, re } of SPEND) {
        const hit = text.match(new RegExp(re, "g")) ?? [];
        const real = hit.filter((h) => !LOCAL.test(h));
        expect(
          real,
          `${rel} names ${what} (${real.join(", ")}). The headless suite must ` +
            `run on an air-gapped machine with no account attached.`,
        ).toEqual([]);
      }
    }
  });
});

// ---------------------------------------------------------------------------
// ISC-423 — ISC-140 restated once `llm.providers` gave a credential two doors
// ---------------------------------------------------------------------------

/**
 * The same anti-criterion as ISC-140, re-derived because the ground moved.
 *
 * ## What ISC-140 bought, and exactly where it stops
 *
 * The guard above greps `test/e2e/ ** / *.test.ts` for a credential-suffixed
 * identifier or a non-loopback `http(s)` URL. It is a good guard and it is
 * still here. It answers ONE question — "does a file whose name ends in
 * `.test.ts`, in one directory, contain a spend-shaped literal" — and this
 * feature moved the answer away from that question in two directions.
 *
 * ## Direction one: the reachable set is bigger than the directory
 *
 * `test/e2e/` does not contain the suite; it contains the suite's ENTRY
 * POINTS. Every e2e file imports `test/support/spawn-cli.ts`, and every one
 * of them reaches `test/fixtures/` by path — `fake-pi.ts` and
 * `scenarios/*.json` are named in all three. A providers-map `fleet.yaml`
 * planted as a fixture is read by the suite and invisible to ISC-140's glob,
 * and a fixture directory is the FIRST place someone would put one, because
 * that is where every other shared input already lives.
 *
 * The scope below is therefore the three roots the headless suite draws on,
 * at any extension. `src/` is deliberately NOT among them: the product's own
 * schema default is `http://omlx.pifleet.internal:8000/v1`, and a guard that
 * banned endpoint literals in production code would fire on the subject
 * matter rather than the defect — the ISC-139 mistake, in a new file.
 *
 * ## Direction two: `api_key_env` is a second spelling for a credential
 *
 * `llm.providers.<name>.api_key_env` NAMES an environment variable, and
 * `base_url` is an endpoint that may be a real vendor's. ISC-140's credential
 * regex was written before that map existed, and it keys on the SUFFIX
 * `API_KEY|SECRET|TOKEN`. `api_key_env: OPENAI_KEY` is a real credential for a
 * real vendor and carries none of those suffixes; neither does `MISTRAL_AUTH`,
 * nor `RALLY_APIKEY`, which is a live variable on the maintainer's own
 * machine. Widening the suffix list is not the fix — it is the same guess one
 * notch out, and the next real key name will miss it too.
 *
 * ## WHY THIS EARNS ITS OWN CRITERION AND IS NOT PEDANTRY. MEASURED.
 *
 * `require_native_tool_calls` DEFAULTS TO TRUE (`schema.ts`), and since
 * ISC-418 the §5.9 gate probes each distinct `(provider, model)` PAIR rather
 * than each model id — so the cost of an `up` now scales with the provider
 * map. What stops the headless suite paying it is NOT the backend. In
 * `up.ts`, `egressNetwork` is assigned from `loadedConfig.config.docker.
 * network` for ANY loaded config, on any backend, and the gate at the bottom
 * of `up` runs whenever `loadedConfig !== null && egressNetwork !== null`.
 * `--backend headless` is nowhere in that condition.
 *
 * Measured on this branch rather than reasoned about, with a providers-map
 * `fleet.yaml` and `up --backend headless`: the run printed the D10 hosted
 * disclosure banner and then exited 3 with
 *
 *     the mandatory native-tool-call probe (SRD §5.9) did not settle whether
 *     model "gpt-oss" emits native tool calls — oMLX unreachable at
 *     https://api.spend-detector.invalid/v1/chat/completions: fetch failed
 *
 * That is a real host-side request to the provider's own `base_url`, from a
 * HEADLESS `up`. Point the same block at a vendor that exists and it is a
 * billable request per pair, per `up`, and the e2e suite calls `up` once per
 * fleet. **The only thing standing between the headless suite and that bill
 * is that no e2e test passes `--config` or writes a `fleet.yaml` into its rig
 * cwd** — and `spawn-cli.ts`'s own docblock advertises the second of those as
 * a supported pattern: "point `cwd` at their own rig directory and put a
 * `fleet.yaml` there". The criterion is one `writeFile` from false.
 *
 * ## What this half does and does not buy, stated because the trade is real
 *
 * It grades LITERALS in the reachable set. It cannot classify an arbitrary
 * environment-variable name — there is no syntactic difference between
 * `ACCEPTANCE_TEST_KEY` (a fake this tree already uses) and `MYCORP_KEY` (a
 * real credential for a company this list has never heard of), and inventing
 * a naming convention for fixtures to obey would be a bigger imposition than
 * the defect. So the key half is deliberately narrow: it names REAL INFERENCE
 * VENDORS, in ISC-139's shape — match the defect, not the category.
 *
 * The general case is the RUNTIME half, in
 * `test/integration/headless-no-spend.test.ts`, which removes the fuel
 * instead of guessing the spelling: it re-runs this suite with every
 * credential-shaped variable stripped from the environment. A test that reads
 * a key through a name no list here anticipated fails there. Neither half
 * subsumes the other — this one runs in milliseconds on every unit run and
 * catches a planted literal before it is ever executed; that one costs a
 * minute and catches what no regex can see.
 */
describe("no file the headless suite reaches names provider spend (ISC-423)", () => {
  /**
   * The roots the headless suite draws on. `test/e2e/` is the suite;
   * `test/support/` and `test/fixtures/` are what it imports and what it
   * loads by path, and a hazard planted in either is a hazard for this suite
   * whichever suite put it there.
   */
  const ROOTS = ["test/e2e", "test/support", "test/fixtures"] as const;

  /**
   * Hosts that cannot be a paid endpoint, by construction rather than by
   * convention.
   *
   * Loopback, RFC 1918 / 5737 / 3927 literals, and the RFC 2606 + RFC 6761
   * reserved names — `.test`, `.example`, `.invalid`, `.localhost` and
   * `example.{com,net,org}` — which the IANA guarantees will never resolve to
   * anyone's server. Plus this project's own two internal names.
   *
   * A RELAXATION over ISC-140, which admits loopback alone, and it is
   * deliberate: these roots are shared with `test/integration/`, whose
   * fixtures legitimately name `tickets.example.test`. A rule those files
   * cannot satisfy is a rule someone eventually deletes. The relaxation costs
   * nothing that matters — every name it admits is unroutable — and the guard
   * still refuses `ollama.com` and `inference.agileguy.ca`, which are the two
   * live endpoints this repository's own test tree already names elsewhere.
   */
  const RESERVED_HOST = [
    /^(?:127\.\d+\.\d+\.\d+|0\.0\.0\.0|\[?::1\]?|localhost)$/,
    /^(?:10\.|192\.168\.|172\.(?:1[6-9]|2\d|3[01])\.|169\.254\.)/,
    /^(?:203\.0\.113\.|198\.51\.100\.|192\.0\.2\.)/,
    /\.(?:test|example|invalid|localhost)$/,
    /^(?:.*\.)?example\.(?:com|net|org)$/,
    /^(?:.*\.)?pifleet\.internal$/,
    /^host\.docker\.internal$/,
    /**
     * A SINGLE-LABEL name — no dot at all. It cannot be a paid endpoint for
     * the same "by construction" reason as every line above it: a provider's
     * API is a delegated FQDN, and a dotless name has no public delegation to
     * be. `localhost` on the first line is already an instance of this rule;
     * this generalises it rather than adding a new kind of exemption.
     *
     * ADDED FOR A REAL FIXTURE, and the docblock above predicted this: the
     * captured `rev-lang-1` artifact under `test/fixtures/envelopes/` is a
     * live reviewer's own words about credential redaction, and it quotes
     * `https://user:p@ss@host` as an EXAMPLE of a URL whose userinfo a bad
     * regex fails to elide. The host it names is the literal word `host`. That
     * is a placeholder in prose, not an endpoint — but the file is a verbatim
     * capture and editing it to satisfy this guard would forge the evidence
     * the fixture exists to preserve.
     *
     * The guard is not weakened where it matters: `ollama.com` and
     * `inference.agileguy.ca`, the two live endpoints named elsewhere in this
     * tree, both have dots and both still fail.
     */
    /^[^.]+$/,
  ];

  /**
   * Environment-variable names belonging to REAL inference vendors.
   *
   * The vendor token must be followed by `_`, so this matches `OPENAI_KEY`
   * and `MISTRAL_AUTH` — neither of which carries an ISC-140 suffix — while
   * `PI_OPENAI_STREAM_IDLE_TIMEOUT_MS` does not match at all, because `\b`
   * does not fire between two word characters. Prose is unaffected: the
   * pattern is upper-case and needs the underscore tail.
   *
   * `GOOGLE` and `CLAUDE` are deliberately ABSENT. `GOOGLE_APPLICATION_
   * CREDENTIALS` is ADC, which `cloud.adc` exists to use and which costs
   * nothing per call, and `CLAUDE_*` is the subject matter of a tool that
   * drives coding agents. Banning either would repeat ISC-139's first draft.
   */
  const VENDOR_KEY =
    /\b(?:OPENAI|ANTHROPIC|MISTRAL|COHERE|GROQ|DEEPSEEK|PERPLEXITY|REPLICATE|HUGGINGFACE|FIREWORKS|OPENROUTER|MOONSHOT|DASHSCOPE|TOGETHER|ANYSCALE|XAI|GEMINI|VERTEX|BEDROCK|AZURE_OPENAI|OLLAMA_CLOUD)_[A-Z0-9_]+\b/g;

  /**
   * A host this guard is able to JUDGE: a DNS name or an IP literal, and
   * nothing else.
   *
   * The three things this rejects are all real and all present in the tree
   * today — `http://<host>:<port>` in `ticket-server.ts`'s docblock,
   * `` `http://${opts.hostname}` `` in the same file, and a bare `http://…`
   * inside an elided example in `dockerfile-copy.ts`. None of them is an
   * endpoint; they are a placeholder, an interpolation and an ellipsis.
   *
   * **This is the guard's principal blind spot and it is named rather than
   * papered over.** An endpoint assembled at runtime —
   * `` `https://${vendorHost}/v1` `` — has no literal host to judge, so this
   * test cannot see it, and neither could ISC-140's. Widening the URL pattern
   * does not help: the vendor name would be in a variable somewhere else in
   * the file, with no `https://` next to it to find it by. That case belongs
   * to the runtime half, which does not care how the URL was spelled because
   * it takes the credential away instead.
   */
  const HOST_LITERAL =
    /^(?:\[[0-9a-f:]+\]|[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)*)$/;

  /** `https://user@api.example.com:443/v1` -> `api.example.com`. */
  function hostOf(url: string): string {
    const authority = url.replace(/^https?:\/\//, "").split(/[/?#]/)[0] ?? "";
    const afterUserinfo = authority.slice(authority.lastIndexOf("@") + 1);
    return afterUserinfo.replace(/:\d+$/, "").toLowerCase();
  }

  async function reachableFiles(): Promise<string[]> {
    const out: string[] = [];
    for (const root of ROOTS) out.push(...(await filesUnder(`${root}/**/*`)));
    return out.sort();
  }

  /**
   * The anti-vacuity gate, and it asserts more than "some files were found".
   *
   * ISC-140 already defends the zero-files case. The failure THIS scope can
   * suffer is subtler and would be silent: a glob that resolves one root and
   * quietly misses the other two still finds plenty of files, and the guard
   * would report green over exactly the directories that were added to it.
   * So every root must contribute.
   */
  test("the scope reaches all three roots the headless suite draws on", async () => {
    const files = await reachableFiles();
    expect(files.length).toBeGreaterThan(20);
    for (const root of ROOTS) {
      expect(
        files.filter((f) => f.startsWith(`${root}/`)).length,
        `no files found under ${root}/; the guard is pointing at nothing there`,
      ).toBeGreaterThan(0);
    }
  });

  test("no reachable file names an endpoint that could bill someone", async () => {
    const offenders: string[] = [];
    for (const rel of await reachableFiles()) {
      const text = await read(rel);
      for (const url of text.match(/https?:\/\/[^\s"'`)\]},]+/g) ?? []) {
        const host = hostOf(url);
        if (!HOST_LITERAL.test(host)) continue;
        if (RESERVED_HOST.some((re) => re.test(host))) continue;
        offenders.push(`${rel}: ${host}`);
      }
    }
    expect(
      offenders,
      `the headless suite reaches a file naming a routable endpoint ` +
        `(${offenders.join("; ")}). It must run on an air-gapped machine with ` +
        `no account attached — and since ISC-418 the §5.9 gate costs a request ` +
        `per (provider, model) pair, so an endpoint reached from here is a bill.`,
    ).toEqual([]);
  });

  test("no reachable file names a real inference vendor's credential variable", async () => {
    const offenders: string[] = [];
    for (const rel of await reachableFiles()) {
      for (const name of (await read(rel)).match(VENDOR_KEY) ?? []) {
        offenders.push(`${rel}: ${name}`);
      }
    }
    expect(
      offenders,
      `the headless suite reaches a file naming a real vendor credential ` +
        `(${offenders.join("; ")}). A fixture's \`api_key_env\` is a second door ` +
        `to the same spend ISC-140 closed; name a variable that cannot resolve ` +
        `to anyone's account.`,
    ).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// ISC-74 — no FleetBackend implementation launches or signals a supervisor
// ---------------------------------------------------------------------------

/**
 * The RESTATED form of ISC-74, and the restatement is the interesting part.
 *
 * As originally worded — *"closing a worker's pane does not stop the worker in
 * rpc mode; the task still settles"* — the criterion could not be tested on
 * this platform, and that was MEASURED rather than assumed. A probe was
 * written: a real tmux server on a private `-L` socket, the supervisor
 * launched from inside the pane, a task dispatched, the session killed
 * mid-turn. It passed in 6 s. It was then DELETED, because removing
 * `detached: true` from `processLauncher.launchDetached` left it GREEN — a
 * `Bun.spawn` child of a pane command shares the pane's pgid and tty, but
 * `tmux kill-session` terminates only the pane's IMMEDIATE process, so the
 * child was orphaned and survived either way. The probe asserted a property
 * that holds unconditionally here, and a guard nobody has seen fail is
 * indistinguishable from one that cannot fail.
 *
 * So the criterion is restated as the ANTI it always structurally was, in
 * ISC-137's shape: the supervisor's lifecycle does not belong to the view
 * layer, and no backend can reach it. `src/backends/types.ts` already says so
 * in its own header — `SupervisorLauncher` is a SEPARATE, backend-independent
 * interface precisely because an earlier design made the supervisor a pane
 * child — and this is what turns that comment into something that can fail.
 *
 * WHAT THIS DOES AND DOES NOT BUY, stated because the trade is real: it grades
 * the MECHANISM (nothing in the view layer can signal a supervisor) rather
 * than the OUTCOME (a closed pane leaves the task settling). The outcome needs
 * a backend arrangement in which pane teardown CAN reach a worker, and none
 * exists. ISC-77/78 own the process-tree facts that make the outcome true.
 */
describe("no FleetBackend implementation launches or signals a supervisor (ISC-74)", () => {
  /**
   * The vocabulary, and why it is this list rather than the word "supervisor".
   *
   * Backends legitimately DISCUSS the supervisor — `tmux/index.ts` explains in
   * its header that supervisors are launched elsewhere, and `cmux/index.ts`
   * writes a shell script whose own comment says a dying viewer must not
   * affect one. Banning the noun would fail on the three files that document
   * the boundary most carefully. What is banned is the machinery: the launcher
   * seam, the kill ladder, and raw signalling.
   */
  const LIFECYCLE = [
    "launchDetached",
    "processLauncher",
    "supervisorArgv",
    "SupervisorLauncher",
    "runKillLadder",
    "killWedged",
    "process.kill",
    "SIGKILL",
    "SIGTERM",
    "safety/kill",
    "safety/reaper",
    "supervisor/launch",
  ] as const;

  test("no backend implementation names any supervisor-lifecycle machinery", async () => {
    // types.ts is DECLARATION, not implementation: it is where
    // `SupervisorLauncher` is defined as separate from `FleetBackend`, which
    // is the very separation under test. Excluding it is the point, not a
    // hole — the implementations are what must not reach the seam.
    const files = (await filesUnder("src/backends/**/*.ts")).filter(
      (f) => f !== "src/backends/types.ts",
    );
    expect(files.length, "no backend files found; the guard is pointing at nothing").toBeGreaterThan(
      3,
    );
    for (const rel of files) {
      const text = stripComments(await read(rel));
      for (const token of LIFECYCLE) {
        expect(
          text.includes(token),
          `${rel} names \`${token}\`. A backend is the VIEW of the fleet; the ` +
            `supervisor's lifecycle belongs to SupervisorLauncher, which is a ` +
            `separate interface for exactly this reason (src/backends/types.ts).`,
        ).toBe(false);
      }
    }
  });

  /**
   * The other half, and without it the guard above is satisfied by a backends
   * tree that has no supervisor machinery because it has nothing at all: the
   * `FleetBackend` INTERFACE must not grow a lifecycle method either. A future
   * `launchWorker(spec)` on this interface would pass the source scan in every
   * existing file while making the criterion false for every backend written
   * afterwards.
   */
  test("the FleetBackend interface declares no lifecycle method", async () => {
    const types = stripComments(await read("src/backends/types.ts"));
    const body = types.slice(types.indexOf("interface FleetBackend"));
    const iface = body.slice(0, body.indexOf("\n}"));
    expect(iface).toContain("createPane"); // the guard is reading the right block
    for (const token of ["launch", "kill", "signal", "spawn"]) {
      expect(
        iface.toLowerCase().includes(token),
        `FleetBackend declares a method naming "${token}". The supervisor ` +
          `lifecycle is SupervisorLauncher's; putting it here makes every ` +
          `backend able to end a worker, which is what ISC-74 forbids.`,
      ).toBe(false);
    }
  });
});
