/**
 * Static anti-criteria over the tree (ISC-139, ISC-165, ISC-199).
 *
 * WHY THESE ARE TESTS AND NOT A CHECKLIST. An `Anti:` criterion asserts an
 * ABSENCE, and an absence is the one claim a passing test suite cannot make on
 * its own — every one of these is satisfied today by a codebase that simply
 * has not done the forbidden thing yet. What earns the criterion is a probe
 * that would NOTICE if it started, so each guard below is mutation-verified:
 * a deliberately planted violation makes it fail. A guard nobody has seen fail
 * is indistinguishable from a guard that cannot fail.
 *
 * ISC-137 and ISC-138 have the same shape and live in
 * `test/unit/rpc-client.test.ts` under "static anti-criteria over src/",
 * because they are specifically about the RPC line splitter. They are not
 * duplicated here.
 */

import { describe, expect, test } from "bun:test";
import { join } from "node:path";

const ROOT = new URL("../../", import.meta.url).pathname;

async function filesUnder(pattern: string): Promise<string[]> {
  const glob = new Bun.Glob(pattern);
  const out: string[] = [];
  for await (const f of glob.scan({ cwd: ROOT })) out.push(f);
  return out.sort();
}

const read = (rel: string): Promise<string> => Bun.file(join(ROOT, rel)).text();

// ---------------------------------------------------------------------------
// ISC-139 — no generated commit, branch, or PR body carries AI attribution
// ---------------------------------------------------------------------------

describe("no generated git artifact carries AI attribution (ISC-139)", () => {
  /**
   * The attribution vocabulary — PHRASING, not vocabulary items.
   *
   * A first draft of this guard banned the bare tokens `claude`, `anthropic`
   * and `copilot` anywhere under `src/`, and it went red immediately on six
   * legitimate sites: `CLAUDE.md` is a FILENAME this tool has to know about,
   * because `src/security/repo-hazards.ts` scans repository instruction files
   * and `src/run/worktree.ts` reasons about a clone that carries one. Banning
   * the name of an agent that pifleet exists to drive would be a guard that
   * fires on the subject matter rather than on the defect.
   *
   * So the patterns below match ATTRIBUTION CONSTRUCTIONS — a trailer, a
   * "generated by" credit, an "AI-assisted" label — which have no legitimate
   * use in this source tree, rather than tokens which plainly do.
   */
  const ATTRIBUTION = [
    /Co-?Authored-?By/i,
    /generated\s+(?:with|by)\s+[^\n]{0,40}?(?:claude|copilot|cursor|codex|chatgpt|gpt-)/i,
    /(?:AI|LLM)-(?:generated|assisted|authored|written)/i,
    /written\s+by\s+(?:an?\s+)?(?:AI|LLM)/i,
  ];

  test("no source file under src/ contains an attribution construction", async () => {
    for (const rel of await filesUnder("src/**/*.ts")) {
      const text = await read(rel);
      for (const re of ATTRIBUTION) {
        expect(re.test(text), `${rel} contains an AI-attribution construction (${re})`).toBe(
          false,
        );
      }
    }
  });

  /**
   * The one git artifact this tool actually generates, pinned by behaviour.
   *
   * `workerBranch` is the whole surface: pifleet writes branch names and
   * nothing else (see the capability pin below). Its output is three inputs
   * joined by slashes, and this asserts exactly that — so a later edit that
   * appends a suffix, a tag, or a credit to the branch name fails here rather
   * than being caught by a reader of `git branch` output months later.
   */
  test("a generated branch name is its three inputs and nothing else", async () => {
    const { workerBranch } = await import("../../src/run/paths.ts");
    expect(workerBranch("fleet", "2026-07-27T00-00-00Z-aaaa", "sre-1")).toBe(
      "fleet/2026-07-27T00-00-00Z-aaaa/sre-1",
    );
    // No component is decorated, and none is dropped.
    expect(workerBranch("p", "r", "w")).toBe("p/r/w");
  });

  /**
   * THE CAPABILITY PIN, and the more useful half of this criterion.
   *
   * Two thirds of what ISC-139 names cannot be violated by this tool as it
   * stands: pifleet creates BRANCHES and WORKTREES, but it never commits and
   * never opens a pull request. Measured by enumerating the git subcommands
   * that appear as argv literals under `src/`: add, branch, checkout, config,
   * diff, log, rev-parse, status, symbolic-ref, worktree — no `commit`, no
   * `push`, no `gh`.
   *
   * That makes "no generated COMMIT or PR BODY carries attribution" VACUOUSLY
   * true, and a criterion that is vacuously true is exactly the kind that
   * rots: someone adds `git commit` for a good reason, the vacuous clause
   * silently becomes a live one, and nothing notices. So the guard does not
   * assert the absence of attribution in commit messages — there are none. It
   * asserts the absence of the CAPABILITY, and fails loudly the day that
   * changes, with a message saying what the new author has to add.
   */
  test("pifleet still generates no commits and no pull requests", async () => {
    const FORBIDDEN = [
      { verb: "commit", re: /["'`]commit["'`]/ },
      { verb: "push", re: /["'`]push["'`]/ },
      { verb: "gh", re: /["'`]gh["'`]/ },
    ];
    /**
     * Comments are stripped before the match, and the reason is a measured
     * false positive rather than a tidy-up.
     *
     * `src/harvest/outbox.ts` acquired the docstring "Every exit that is not
     * the final `push` closes the descriptor first" — prose about
     * `Array.prototype.push`, in backticks because that is how one spells a
     * method name in a comment. The pin read it as an argv literal and failed
     * the build. The criterion is about a git subcommand appearing as an ARGV
     * LITERAL; a method name in a docstring is not one, and forcing prose to
     * avoid ordinary English to appease a regex makes the code worse and the
     * guard less trusted.
     *
     * Stripped CONSERVATIVELY, so the tightening cannot hide a real call:
     * block comments, and whole-line `//` comments only. A TRAILING comment is
     * deliberately left in the scanned text — `spawn(["git", "push"]) // ok`
     * still fails, which is the direction to err in.
     */
    const stripComments = (src: string): string =>
      src
        .replace(/\/\*[\s\S]*?\*\//g, " ")
        .replace(/^[ \t]*\/\/.*$/gm, " ");
    for (const rel of await filesUnder("src/**/*.ts")) {
      const text = stripComments(await read(rel));
      for (const { verb, re } of FORBIDDEN) {
        expect(
          re.test(text),
          `${rel} appears to invoke git/gh "${verb}". ISC-139's commit and ` +
            `pull-request clauses were vacuous because this tool generated ` +
            `neither. If that is changing, extend the attribution guard above ` +
            `to cover the generated message body, then update this pin.`,
        ).toBe(false);
      }
    }
  });
});

// ---------------------------------------------------------------------------
// ISC-165 — a `:ro` refusal must be a refusal, not an absence
// ---------------------------------------------------------------------------

/**
 * Split a test file into per-test bodies. Crude on purpose: an exact parse
 * would need the TypeScript AST, and the property being checked is a
 * co-occurrence within one test, which chunking on the test boundary captures.
 * Over-chunking would only ever make the guard STRICTER (a read assertion in a
 * neighbouring test would not be credited), never more permissive.
 */
function testBodies(text: string): string[] {
  return text.split(/\n\s*(?:it|test)\s*\(/);
}

describe("a :ro refusal test proves the mount was readable first (ISC-165)", () => {
  /** A write was rejected: the command came back nonzero. */
  const REFUSAL = /\.code\s*\)\s*\.not\.toBe\(\s*0\s*\)|\.code\s*\)\s*\.toBe\(\s*[1-9]/;
  /** Something was actually read back out of the mount. */
  const READ = /\.stdout\s*\)\s*\.toContain\(|readFile\(/;

  test("every :ro write-refusal test also asserts a successful read", async () => {
    const files = [...(await filesUnder("test/**/*.test.ts"))];
    let checked = 0;
    for (const rel of files) {
      const text = await read(rel);
      if (!text.includes(":ro")) continue;
      for (const body of testBodies(text)) {
        if (!body.includes(":ro")) continue;
        if (!REFUSAL.test(body)) continue; // not a refusal test; nothing to prove
        checked += 1;
        const name = body.slice(0, body.indexOf("\n")).trim();
        expect(
          READ.test(body),
          `${rel}: a :ro refusal test asserts a write was rejected but never ` +
            `reads from the mount, so it passes identically against a mount ` +
            `that is simply ABSENT (an empty mount refuses writes too). ` +
            `Read a host-written file first. Test: ${name}`,
        ).toBe(true);
      }
    }
    // If this reaches zero the guard has stopped guarding anything — the
    // refusal tests were renamed or deleted and nobody noticed.
    expect(checked, "no :ro refusal test was found to check").toBeGreaterThan(0);
  });
});

// ---------------------------------------------------------------------------
// ISC-199 — no assertion encodes a platform-specific POSIX spelling
// ---------------------------------------------------------------------------

describe("no assertion encodes a platform-specific POSIX spelling (ISC-199)", () => {
  /**
   * `ps` is the standing example and the one the criterion names: a detached
   * process prints `??` for its tty on macOS and `?` on Linux, and `ps -o
   * sess=` prints 0 for everything on macOS while Linux reports a real session
   * id. An assertion that pins either spelling is green on the machine it was
   * written on and red on the other, which is the same "suite you learn to
   * discount" failure ISC-266 is about, arrived at through portability.
   *
   * Spawning `ps` is fine and several tests legitimately do. Comparing its
   * output against a hardcoded platform spelling is what this bans.
   */
  const PLATFORM_SPELLINGS = [
    { what: "a literal ?? tty spelling", re: /toBe\(\s*["'`]\?\??["'`]\s*\)|toContain\(\s*["'`]\?\?["'`]\s*\)/ },
    { what: "an exact ps session-id value", re: /sess=[^"'`\n]*["'`]\s*\)\s*\.toBe\(/ },
  ];

  test("no test asserts a hardcoded ps output spelling", async () => {
    for (const rel of await filesUnder("test/**/*.test.ts")) {
      const text = await read(rel);
      for (const { what, re } of PLATFORM_SPELLINGS) {
        expect(re.test(text), `${rel} asserts ${what}; it will differ across platforms`).toBe(
          false,
        );
      }
    }
  });
});

// ---------------------------------------------------------------------------
// ISC-140 — the headless acceptance suite costs nothing and dials nothing
// ---------------------------------------------------------------------------

describe("no headless acceptance test needs provider spend or a cloud endpoint (ISC-140)", () => {
  /**
   * `test/e2e/` IS the headless acceptance suite — `lifecycle.test.ts` opens by
   * naming its own contract, "no Docker, no network, no GUI (ISC-19,
   * ISC-128)". ISC-21 already holds the network half of that. This is the
   * money half, and the two fail differently: a test that needs egress fails
   * closed on an air-gapped runner and everybody finds out, while a test that
   * needs provider spend PASSES and quietly bills someone. That asymmetry is
   * why it earns its own probe rather than riding on ISC-21's.
   *
   * Measured at the time of writing: the only environment variables the suite
   * touches are `PIFLEET_RUNS_DIR` and `PIFLEET_PI_*`, and it contains no URL
   * at all.
   */
  const SPEND = [
    { what: "a provider API key", re: /\b[A-Z][A-Z0-9_]*(?:API_KEY|SECRET|TOKEN)\b/ },
    { what: "an http(s) endpoint", re: /https?:\/\// },
  ];
  /** Localhost is not a cloud endpoint and not spend; a fixture may name it. */
  const LOCAL = /^https?:\/\/(?:127\.0\.0\.1|localhost|\[::1\])/;

  test("the e2e suite names no provider credential and no remote endpoint", async () => {
    const files = await filesUnder("test/e2e/**/*.test.ts");
    expect(files.length, "no e2e files found; the guard is pointing at nothing").toBeGreaterThan(
      0,
    );
    for (const rel of files) {
      const text = await read(rel);
      for (const { what, re } of SPEND) {
        const hit = text.match(new RegExp(re, "g")) ?? [];
        const real = hit.filter((h) => !LOCAL.test(h));
        expect(
          real,
          `${rel} names ${what} (${real.join(", ")}). The headless suite must ` +
            `run on an air-gapped machine with no account attached.`,
        ).toEqual([]);
      }
    }
  });
});
